apiVersion: 1
datasources:
  - name: Postgres
    type: postgres
    access: proxy
    isDefault: true
    url: postgres:5432
    user: airflow
    secureJsonData:
      password: airflow
    jsonData:
      database: airflow
      sslmode: disable
